export const BARANGAYS = [
  "Burol",
  "Burol I",
  "Burol II",
  "Burol III",
  "Datu Esmael",
  "Emmanuel Bergado I",
  "Emmanuel Bergado II",
  "Fatima I",
  "Fatima II",
  "Fatima III",
  "H-2",
  "Langkaan I",
  "Langkaan II",
  "Luzviminda I",
  "Luzviminda II",
  "Paliparan I",
  "Paliparan II",
  "Paliparan III",
  "Sabang",
  "Saint Peter I",
  "Saint Peter II",
  "Salawag",
  "Salitran I",
  "Salitran II",
  "Salitran III",
  "Salitran IV",
  "Sampaloc I",
  "Sampaloc II",
  "Sampaloc III",
  "Sampaloc IV",
  "Sampaloc V",
  "San Agustin I",
  "San Agustin II",
  "San Agustin III",
  "San Andres I",
  "San Andres II",
  "San Antonio De Padua I",
  "San Antonio De Padua II",
  "San Dionisio (Barangay 1)",
  "San Esteban (Barangay 4)",
  "San Francisco I",
  "San Francisco II",
  "San Isidro Labrador I",
  "San Isidro Labrador II",
  "San Jose",
  "San Juan (San Juan I)",
  "San Lorenzo Ruiz I",
  "San Lorenzo Ruiz II",
  "San Luis I",
  "San Luis II",
  "San Manuel I",
  "San Manuel II",
  "San Mateo",
  "San Miguel",
  "San Miguel II",
  "San Nicolas I",
  "San Nicolas II",
  "San Roque (Sta. Cristina II)",
  "San Simon (Barangay 7)",
  "Santa Cristina I",
  "Santa Cristina II",
  "Santa Cruz I",
  "Santa Cruz II",
  "Santa Fe",
  "Santa Lucia (San Juan II)",
  "Santa Maria (Barangay 20)",
  "Santo Cristo (Barangay 3)",
  "Santo Niño I",
  "Santo Niño II",
  "Victoria Reyes Pag-asa",
  "Zone I (Pob.)",
  "Zone I-A (Pob.)",
  "Zone I-B",
  "Zone II (Pob.)",
  "Zone III (Pob.)",
  "Zone IV (Pob.)",
];

export const SECURITY_QUESTIONS = [
  "What is your mother’s maiden name?",
  "What was the name of your first pet?",
  "What was the make and model of your first car?",
  "What is your favorite teacher’s name?",
  "In what city were you born?",
  "What was the name of your elementary school?",
  "What is your father’s middle name?",
  "What is your favorite movie?",
  "What is the name of your best childhood friend?",
  "What street did you live on in third grade?",
  "What is the title of your favorite book?",
  "What is your dream job?",
  "What is the name of your childhood hero?",
  "Where did you go on your first vacation?",
  "What was your first mobile phone brand?",
  "What is the name of the first company you worked for?",
  "What was your favorite subject in school?",
  "Who was your favorite cartoon character as a child?",
  "What’s the nickname only your family uses for you?",
  "What is the name of the hospital where you were born?",
];
